version: "3.8"

services:
  intranet-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: intranet
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf # Mount custom postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"] # Use custom config
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
