version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      DB_HOST: postgres-db
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - intranet-network
    restart: always

networks:
  intranet-network:
    external: true

volumes:
  postgres_data:
    driver: local
