export const formFields = [
  { name: "armyNo", label: "Army No", type: "text", required: true },
  { name: "rank", label: "Rank", type: "text", required: true },
  { name: "name", label: "Name", type: "text", required: true },
  { name: "course", label: "Course", type: "text", required: true },
  { name: "mSubs", label: "M Subs", type: "number" },
  { name: "saving", label: "Saving", type: "number" },
  { name: "cFund", label: "C Fund", type: "number" },
  { name: "messing", label: "Messing", type: "number" },
  { name: "eMessing", label: "E Messing", type: "number" },
  { name: "suiGasPerDay", label: "Sui Gas Per Day", type: "number" },
  { name: "suiGas25Percent", label: "Sui Gas 25 Percent", type: "number" },
  { name: "teaBarMCS", label: "Tea Bar MCS", type: "number" },
  { name: "diningHallCharges", label: "Dining Hall Charges", type: "number" },
  { name: "swpr", label: "SWPR", type: "number" },
  { name: "laundry", label: "Laundry", type: "number" },
  { name: "garMess", label: "Gar Mess", type: "number" },
  { name: "roomMaint", label: "Room Maint", type: "number" },
  {
    name: "elecCharges160Block",
    label: "Elec Charges 160 Block",
    type: "number",
  },
  { name: "internet", label: "Internet", type: "number" },
  { name: "svcCharges", label: "SVC Charges", type: "number" },
  { name: "suiGasBOQs", label: "Sui Gas BOQs", type: "number" },
  { name: "suiGas166CD", label: "Sui Gas 166CD", type: "number" },
  { name: "suiGas166Block", label: "Sui Gas 166 Block", type: "number" },
  { name: "lounge160", label: "Lounge 160", type: "number" },
  { name: "rentCharges", label: "Rent Charges", type: "number" },
  { name: "furMaint", label: "Fur Maint", type: "number" },
  { name: "suiGasElecFTs", label: "Sui Gas Elec FTs", type: "number" },
  { name: "matCharges", label: "Mat Charges", type: "number" },
  { name: "hcWA", label: "HC WA", type: "number" },
  { name: "gym", label: "Gym", type: "number" },
  { name: "cafeMaintCharges", label: "Cafe Maint Charges", type: "number" },
  { name: "dineOut", label: "Dine Out", type: "number" },
  { name: "payamber", label: "Payamber", type: "number" },
  {
    name: "studentSocietiesFund",
    label: "Student Societies Fund",
    type: "number",
  },
  { name: "dinnerNiJSCMCC69", label: "Dinner Ni JSCMCC 69", type: "number" },
  { name: "currentBill", label: "Current Bill", type: "number" },
  { name: "arrear", label: "Arrear", type: "number" },
  { name: "receiptNo", label: "Receipt No", type: "text", required: true },
  { name: "amountReceived", label: "Amount Received", type: "number" },
];
